### PR TITLE
add Italian translation

### PR DESCRIPTION
**Pull request by Marocco2**

### CODE REVIEW

**Comment by Marocco2** [comment]
@Marocco2 now it's ok

**Comment by FrayxRulez** [comment]
We don't actually need localization because the app is still WIP and many pages, controls names, ecc will change.

**Comment by Marocco2** [comment]
@FrayxRulez Don't worry. I'll update it if there are changes

**Comment by ikarago** [comment]
Thanks for the help! :) 
We decided early on to wait with translations until we've got the basics down and steady. Like Fela said; a lot can change (especially in the fase we're currently in). For now we'll keep it closed. We'll let you know on the Insiders-chat and here on the GitHub once we're open for translations. ;)

**Comment by Marocco2** [comment]
@ikarago Ok, thank you 👍

**Pull request closed without merging**
